name: radio_grouped_buttons
description: New Grouped Radio Buttons Widget. Using this widget grouping and electing list of amout buttons will be easy.
version: 1.0.0
homepage: https://github.com/Dineth95/radio_grouped_buttons

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
