name: radio_grouped_buttons
description: New Grouped Radio Buttons Widget
version: 0.0.1
author: Dineth Prabashwara<prabhwaradineth@gmail.com>
homepage: https://github.com/Dineth95/radio_grouped_buttons

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
